### ISSUE TITLE
build fails for filter example - no such package

### ISSUE THREAD

**Issue by kjyoti** [envoyproxy/envoy-filter-example#85]
/envoy-filter-example$ bazel build //:envoy
Starting local Bazel server and connecting to it...
ERROR: /home/jyoti/.cache/bazel/_bazel_jyoti/d7dbc3ad28d2496ca23a589bf2a3c01f/external/envoy/bazel/foreign_cc/BUILD:8:1: no such package '@com_github_gperftools_gperftools//': Traceback (most recent call last):
	File "/home/jyoti/.cache/bazel/_bazel_jyoti/d7dbc3ad28d2496ca23a589bf2a3c01f/external/bazel_tools/tools/build_defs/repo/http.bzl", line 55
		patch(ctx)
	File "/home/jyoti/.cache/bazel/_bazel_jyoti/d7dbc3ad28d2496ca23a589bf2a3c01f/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 89, in patch
		fail(("Error applying patch command %...)))
Error applying patch command ./autogen.sh:
./autogen.sh: 3: ./autogen.sh: autoreconf: not found
 and referenced by '@envoy//bazel/foreign_cc:gperftools_build'
ERROR: Analysis of target '//:envoy' failed; build aborted: no such package '@com_github_gperftools_gperftools//': Traceback (most recent call last):
	File "/home/jyoti/.cache/bazel/_bazel_jyoti/d7dbc3ad28d2496ca23a589bf2a3c01f/external/bazel_tools/tools/build_defs/repo/http.bzl", line 55
		patch(ctx)
	File "/home/jyoti/.cache/bazel/_bazel_jyoti/d7dbc3ad28d2496ca23a589bf2a3c01f/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 89, in patch
		fail(("Error applying patch command %...)))
Error applying patch command ./autogen.sh:
./autogen.sh: 3: ./autogen.sh: autoreconf: not found
INFO: Elapsed time: 25.181s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 149 targets configured)

Please help me resolve this error

**Comment by kuroneko25** [comment]
Also running into this error.

**Comment by dio** [comment]
@kjyoti @kuroneko25 seems like you don't have `autoreconf` on your machine. Could you let us know the platform you use to build this project? Thanks!

**Comment by catalin-me** [comment]
@kjyoti @kuroneko25 Make sure to install the required dependencies and check to see if the issue persists:

#### Ubuntu

```bash
sudo apt-get install libtool cmake automake autoconf make ninja-build curl unzip virtualenv
```

#### Mac OS
```bash
brew install coreutils wget cmake libtool go bazel automake ninja clang-format autoconf aspell
```

**Comment by MOURYA00** [comment]
Is there any way to fix it on windows?
